# 
# Synthesis run script generated by Vivado
# 

set_param simulator.modelsimInstallPath C:/ProgramData/ModelSim/win32pe
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/tonhi/Project/Computer-Organization/Projects/CPU31/CPU31.cache/wt [current_project]
set_property parent.project_path C:/Users/tonhi/Project/Computer-Organization/Projects/CPU31/CPU31.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files -quiet c:/Users/tonhi/Project/Computer-Organization/Projects/CPU31/CPU31.srcs/sources_1/ip/imem/imem.dcp
set_property used_in_implementation false [get_files c:/Users/tonhi/Project/Computer-Organization/Projects/CPU31/CPU31.srcs/sources_1/ip/imem/imem.dcp]
add_files -quiet c:/Users/tonhi/Project/Computer-Organization/Projects/CPU31/CPU31.srcs/sources_1/ip/dmem/dmem.dcp
set_property used_in_implementation false [get_files c:/Users/tonhi/Project/Computer-Organization/Projects/CPU31/CPU31.srcs/sources_1/ip/dmem/dmem.dcp]
read_verilog -library xil_defaultlib {
  C:/Users/tonhi/Project/Computer-Organization/Projects/CPU31/CPU31.srcs/sources_1/new/alu.v
  C:/Users/tonhi/Project/Computer-Organization/Projects/CPU31/CPU31.srcs/sources_1/new/decoder.v
  C:/Users/tonhi/Project/Computer-Organization/Projects/CPU31/CPU31.srcs/sources_1/new/regfile.v
  C:/Users/tonhi/Project/Computer-Organization/Projects/CPU31/CPU31.srcs/sources_1/new/cpu.v
  C:/Users/tonhi/Project/Computer-Organization/Projects/CPU31/CPU31.srcs/sources_1/new/sccomp_dataflow.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top sccomp_dataflow -part xc7a100tcsg324-1


write_checkpoint -force -noxdef sccomp_dataflow.dcp

catch { report_utilization -file sccomp_dataflow_utilization_synth.rpt -pb sccomp_dataflow_utilization_synth.pb }
